name: Test pushes and PRs
on: [push, pull_request]
jobs:
  test:
    name: Run tests.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Lint core and features
        run: |
          npm install -g eslint
          npm i
          eslint --ext .ts,.js,.tsx,.jsx .
      - name: Build core and features
        run: ./build.js
      - name: Test core and features
        run: xvfb-run --auto-servernum ./build.js test
      - name: Test android
        working-directory: android
        run: ./gradlew test
